Charger le fichier CSV :

In [1]:
import pandas as pd 
df = pd.read_csv("tickets_demo.csv")
df.head()

,ticket_id,titre,statut,priorite,responsable,date_creation,date_limite,type_t
0,T001,Ticket exemple 1,bloque,critique,Fatime,2026-07-01,2026-07-04,bug
1,T002,Ticket exemple 2,A faire,moyenne,Fatime,2026-05-15,2026-07-04,amelioration
2,T003,Ticket exemple 3,bloque,faible,NaN,2026-06-11,2026-07-04,amelioration
3,T004,Ticket exemple 4,bloque,faible,NaN,2026-05-18,2026-07-04,Tache
4,T005,Ticket exemple 5,bloque,elevee,Mouad,2026-06-06,2026-07-04,amelioration

Convertir les colonnes de date en vrai dates :

In [2]:
df["date_creation"] = pd.to_datetime(df["date_creation"])
df["date_limite"] = pd.to_datetime(df["date_limite"])

Creation de nouvelle colonne pour les tickets en retard :

In [3]:
from datetime import date

aujourd_hui = pd.Timestamp(date.today())
df["en_retard"] = (df["date_limite"] < aujourd_hui) & (df["statut"] != "termine")
df.head()

,ticket_id,titre,statut,priorite,responsable,date_creation,date_limite,type_t,en_retard
0,T001,Ticket exemple 1,bloque,critique,Fatime,2026-07-01,2026-07-04,bug,True
1,T002,Ticket exemple 2,A faire,moyenne,Fatime,2026-05-15,2026-07-04,amelioration,True
2,T003,Ticket exemple 3,bloque,faible,NaN,2026-06-11,2026-07-04,amelioration,True
3,T004,Ticket exemple 4,bloque,faible,NaN,2026-05-18,2026-07-04,Tache,True
4,T005,Ticket exemple 5,bloque,elevee,Mouad,2026-06-06,2026-07-04,amelioration,True

Afficher les tickets en retard :

In [4]:
df[df["en_retard"] == True][["ticket_id", "date_limite", "statut"]]

   ticket_id date_limite    statut
0       T001  2026-07-04    bloque
1       T002  2026-07-04   A faire
2       T003  2026-07-04    bloque
3       T004  2026-07-04    bloque
4       T005  2026-07-04    bloque
6       T007  2026-06-21    bloque
7       T008  2026-06-25    bloque
8       T009  2026-06-20    bloque
10      T011  2026-07-08    bloque
13      T014  2026-05-30  En cours
15      T016  2026-06-07    bloque
16      T017  2026-07-19  En cours
17      T018  2026-06-14    bloque
18      T019  2026-07-20  En cours
19      T020  2026-07-02    bloque
20      T021  2026-06-16    bloque
21      T022  2026-07-03    bloque
22      T023  2026-07-04   A faire
23      T024  2026-07-16  En cours
24      T025  2026-06-17    bloque
26      T027  2026-06-13   A faire
27      T028  2026-05-26    bloque
29      T030  2026-05-29  En cours
30      T031  2026-07-12   A faire
31      T032  2026-05-27  En cours
33      T034  2026-07-14    bloque
34      T035  2026-06-16    bloque
35      T036  2026-07-02  En cours
36      T037  2026-06-29    bloque
37      T038  2026-06-12    bloque
38      T039  2026-06-07  En cours

In [5]:
total_tickets = len(df)
tickets_termines = len(df[df["statut"] == "termine"])
tickets_bloques = len(df[df["statut"] == "bloque"])
tickets_en_retard = len(df[df["en_retard"] == True])

print(f"tickets totales : {total_tickets}")
print(f"tickets termines :{tickets_termines}")
print(f"tickets bloques : {tickets_bloques}")
print(f"tickets en retard : {tickets_en_retard}")

tickets totales : 40
tickets termines :4
tickets bloques : 22
tickets en retard : 31

In [6]:
df["priorite"].value_counts()

priorite
faible      14
critique    13
moyenne      8
elevee       5
Name: count, dtype: int64

In [7]:
print(df["responsable"].head(15))
print(df["responsable"].isna().sum())

0     Fatime
1     Fatime
2        NaN
3        NaN
4      Mouad
5       Eman
6      Mouad
7      Douae
8     Fatime
9        NaN
10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
Name: responsable, dtype: object
13

Creation de colonne "sans responsable"

In [8]:
df["sans_responsable"] = df["responsable"].isna()
df.head()

,ticket_id,titre,statut,priorite,responsable,date_creation,date_limite,type_t,en_retard,sans_responsable
0,T001,Ticket exemple 1,bloque,critique,Fatime,2026-07-01,2026-07-04,bug,True,False
1,T002,Ticket exemple 2,A faire,moyenne,Fatime,2026-05-15,2026-07-04,amelioration,True,False
2,T003,Ticket exemple 3,bloque,faible,NaN,2026-06-11,2026-07-04,amelioration,True,True
3,T004,Ticket exemple 4,bloque,faible,NaN,2026-05-18,2026-07-04,Tache,True,True
4,T005,Ticket exemple 5,bloque,elevee,Mouad,2026-06-06,2026-07-04,amelioration,True,False

Creation de colonne "Critique" :

In [9]:
df["critique"] = df["priorite"] == "critique"
df.head()

,ticket_id,titre,statut,priorite,responsable,date_creation,date_limite,type_t,en_retard,sans_responsable,critique
0,T001,Ticket exemple 1,bloque,critique,Fatime,2026-07-01,2026-07-04,bug,True,False,True
1,T002,Ticket exemple 2,A faire,moyenne,Fatime,2026-05-15,2026-07-04,amelioration,True,False,False
2,T003,Ticket exemple 3,bloque,faible,NaN,2026-06-11,2026-07-04,amelioration,True,True,False
3,T004,Ticket exemple 4,bloque,faible,NaN,2026-05-18,2026-07-04,Tache,True,True,False
4,T005,Ticket exemple 5,bloque,elevee,Mouad,2026-06-06,2026-07-04,amelioration,True,False,False

In [10]:
synthese = f"""
Synthèse du projet — {date.today().strftime('%d/%m/%Y')}

Total tickets : {total_tickets}
Terminés : {tickets_termines}
Bloqués : {tickets_bloques}
En retard : {tickets_en_retard}
Sans responsable : {df['sans_responsable'].sum()}
Tickets critiques : {df['critique'].sum()}

Points d'attention principaux :
- {tickets_en_retard} ticket(s) dépassent leur date limite et nécessitent une action rapide.
- {df['sans_responsable'].sum()} ticket(s) n'ont pas de responsable assigné.
"""

print(synthese)

Synthèse du projet — 22/07/2026

Total tickets : 40
Terminés : 4
Bloqués : 22
En retard : 31
Sans responsable : 13
Tickets critiques : 13

Points d'attention principaux :
- 31 ticket(s) dépassent leur date limite et nécessitent une action rapide.
- 13 ticket(s) n'ont pas de responsable assigné.